version: '3.8'

services:
  test-majoo:
    container_name: test-majoo
    image: majoo/test-majoo:latest
    restart: always
    ports:
      - '8080:8080'
    networks:
      - test-majoo
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '8080'
    depends_on:
      - test-majoo-db
      - test-majoo-redis
  test-majoo-db:
    image: mysql:5.7
    restart: always
    ports:
      - '3308:3306'
    environment:
      MYSQL_DATABASE: 'test-majoo'
      MYSQL_USER: 'majoo'
      MYSQL_PASSWORD: 'majoo'
      MYSQL_ROOT_PASSWORD: 'majoo'
    volumes:
      - test-majoo-db:/var/lib/mysql
    networks:
      - test-majoo
  test-majoo-redis:
    image: redis:latest
    restart: always
    command: redis-server --save 60 1 --requirepass majoo --loglevel warning
    ports:
      - '6378:6379'
    networks:
      - test-majoo
    volumes:
      - test-majoo-redis:/data

volumes:
  test-majoo-db:
  test-majoo-redis:

networks:
  test-majoo:
    external: true
